[package]
name = "dugong"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dugong-graphlib = { path = "../dugong-graphlib" }
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
gag = "1.0.0"
