[workspace]
resolver = "2"
members = [
  "crates/merman",
  "crates/merman-core",
  "crates/merman-cli",
  "crates/merman-render",
  "crates/dugong",
  "crates/dugong-graphlib",
  "crates/xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
lalrpop = "0.20.2"
lalrpop-util = "0.20.2"
logos = "0.14.4"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
serde_yaml = "0.9.34"
thiserror = "2.0.11"
tracing = "0.1.41"
futures = "0.3.31"
lol_html = "2.7.1"
url = "2.5.4"
uuid = { version = "1.12.1", features = ["v4"] }
chrono = { version = "0.4.40", features = ["clock"] }
