[workspace]
resolver = "2"
members = [
  "crates/merman",
  "crates/merman-core",
  "crates/merman-cli",
  "crates/merman-render",
  "crates/dugong",
  "crates/dugong-graphlib",
  "crates/roughr",
  "crates/xtask",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
base64 = "0.22.1"
lalrpop = "0.20.2"
lalrpop-util = "0.20.2"
logos = "0.14.4"
pulldown-cmark = "0.12.2"
regex = "1.11.1"
roxmltree = "0.20.0"
roughr = "0.12.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138", features = ["preserve_order"] }
serde_yaml = "0.9.34"
thiserror = "2.0.11"
tracing = "0.1.41"
futures = "0.3.31"
lol_html = "2.7.1"
url = "2.5.4"
uuid = { version = "1.12.1", features = ["v4"] }
chrono = { version = "0.4.40", features = ["clock"] }

[patch.crates-io]
roughr = { path = "crates/roughr" }
