[workspace]
resolver = "2"
members = [
  "crates/merman",
  "crates/merman-core",
  "crates/merman-cli",
  "crates/merman-render",
  "crates/dugong",
  "crates/dugong-graphlib",
  "crates/manatee",
  "crates/roughr",
  "crates/xtask",
]
exclude = ["repo-ref/mermaid-rs-renderer", "repo-ref/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Mingzhen Zhuang <superfrankie621@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/Latias94/merman"
homepage = "https://github.com/Latias94/merman"
rust-version = "1.87"

[workspace.dependencies]
base64 = "0.22.1"
euclid = "0.22"
htmlize = { version = "1.0.6", features = ["unescape"] }
indexmap = { version = "2.2.6", features = ["serde"] }
lalrpop = "0.20.2"
lalrpop-util = "0.20.2"
logos = "0.14.4"
nalgebra = { version = "0.34.1", default-features = false, features = ["std"] }
pulldown-cmark = "0.12.2"
regex = "1.11.1"
roxmltree = "0.20.0"
rustc-hash = "2.1.1"
ryu-js = "1.0.2"
roughr = "0.12.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138", features = ["preserve_order"] }
serde_yaml = "0.9.34"
json5 = "0.4.1"
thiserror = "2.0.11"
tracing = "0.1.41"
futures = "0.3.31"
hashbrown = "0.16.1"
lol_html = "2.7.1"
url = "2.5.4"
uuid = { version = "1.12.1", features = ["v4"] }
chrono = { version = "0.4.40", features = ["clock"] }
image = { version = "0.25", default-features = false, features = ["jpeg"] }
resvg = "0.46.0"
usvg = "0.46.0"
tiny-skia = "0.11.4"
svg2pdf = "0.13.0"
unicode-width = "0.2.2"

# Workspace crates (publishable). Keeping versions explicit makes `cargo publish` work without
# duplicating version requirements across crates.
merman = { path = "crates/merman", version = "0.1.0" }
merman-core = { path = "crates/merman-core", version = "0.1.0" }
merman-render = { path = "crates/merman-render", version = "0.1.0" }
merman-cli = { path = "crates/merman-cli", version = "0.1.0" }
dugong = { path = "crates/dugong", version = "0.1.0" }
dugong-graphlib = { path = "crates/dugong-graphlib", version = "0.1.0" }
manatee = { path = "crates/manatee", version = "0.1.0" }

[patch.crates-io]
roughr = { path = "crates/roughr" }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
