[package]
name = "merman-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "CLI to parse/layout/render Mermaid diagrams to SVG/PNG/JPG/PDF (headless)."
documentation = "https://docs.rs/merman-cli"
readme = "../../README.md"
keywords = ["mermaid", "diagrams", "svg", "cli", "headless"]
categories = ["command-line-utilities", "visualization"]

[dependencies]
futures.workspace = true
merman.workspace = true
merman-render.workspace = true
serde.workspace = true
serde_json.workspace = true
image = { version = "0.25", default-features = false, features = ["jpeg"] }
resvg = "0.46.0"
usvg = "0.46.0"
tiny-skia = "0.11.4"
svg2pdf = "0.13.0"

[dev-dependencies]
assert_cmd = "2.0.16"
tempfile = "3.14.0"
png = "0.17.16"
