[package]
name = "merman-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
merman = { path = "../merman" }
merman-render = { path = "../merman-render" }
serde.workspace = true
serde_json.workspace = true
