[package]
name = "merman-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
dugong = { path = "../dugong" }
indexmap.workspace = true
merman-core = { path = "../merman-core" }
pulldown-cmark.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
roughr.workspace = true
ryu-js.workspace = true
url.workspace = true

[dev-dependencies]
futures.workspace = true

[features]
flowchart_root_pack = []
