[package]
name = "merman-render"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
dugong = { path = "../dugong" }
merman-core = { path = "../merman-core" }
pulldown-cmark.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
futures.workspace = true
