[package]
name = "merman"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Rust, headless Mermaid implementation (1:1 parity; pinned to mermaid@11.12.2)."
documentation = "https://docs.rs/merman"
readme = "../../README.md"
keywords = ["mermaid", "diagrams", "svg", "parser", "headless"]
categories = ["parser-implementations", "visualization"]

[features]
default = []
render = ["dep:merman-render", "dep:thiserror"]
raster = [
    "render",
    "dep:image",
    "dep:resvg",
    "dep:usvg",
    "dep:tiny-skia",
    "dep:svg2pdf",
]

[dependencies]
merman-core.workspace = true
merman-render = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
image = { workspace = true, optional = true }
resvg = { workspace = true, optional = true }
usvg = { workspace = true, optional = true }
tiny-skia = { workspace = true, optional = true }
svg2pdf = { workspace = true, optional = true }
