[package]
name = "merman"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Rust, headless, 1:1 re-implementation of Mermaid (pinned to mermaid@11.12.2)."
documentation = "https://docs.rs/merman"
readme = "../../README.md"
keywords = ["mermaid", "diagrams", "svg", "parser", "headless"]
categories = ["parser-implementations", "visualization"]

[features]
default = []
render = ["dep:merman-render", "dep:thiserror"]

[dependencies]
merman-core.workspace = true
merman-render = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
